package com.al_enterprise.dataclasses


data class DeviceData(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val id: String? = null,
    val name: String? = null,
    val ipAddress: String? = null,
    val ipAddressV6: String? = null,
    val friendlyName: String? = null,
    val macAddress: String? = null,
    val serialNumber: String? = null,
    val deviceFamily: String? = null,
    val type: String? = null,
    val physicalLocation: String? = null,
    val description: String? = null,
    val systemContact: String? = null,
    val location: Location? = null,
    val floorElevation: Double? = null,
    val deviceStatus: String? = null,
    val currentSwVer: String? = null,
    val workingMode: String? = null,
    val lastSeenTime: Long? = null,
    val imageLocation: String? = null,
    val licenseStatus: String? = null,
    val autoChoosingLicenseMode: String? = null,
    val markPremium: Boolean? = null,
    val managementMode: String? = null,
    val isRap: Boolean? = null,
    val vpnSettingName: String? = null,
    val isAutoRegistered: Boolean? = null,
    val vcSerialNumber: String? = null,
    val calculatedMacAddress: String? = null,
    val organization: String? = null,
    val site: String? = null,
    val group: String? = null,
    val building: String? = null,
    val floor: String? = null,
    val license: License? = null,
    val deviceLabels: List<DeviceLabel>? = null,
    val lastEventReceivedAt: Long? = null,
    val wiredPortLinkStatus: String? = null,
    val iotStatus: String? = null,
    val ipMode: String? = null,
    val meshEnable: Boolean? = null,
    val meshRole: String? = null,
    val meshIsRoot: Boolean? = null,
    val meshBand: String? = null,
    val meshEssid: String? = null,
    val meshPassphrase: String? = null,
    val ipv4Netmask: String? = null,
    val ipv4Gateway: String? = null,
    val ipv4DeviceDNS: String? = null,
    val ipv6Prefixlen: String? = null,
    val ipv6Gateway: String? = null,
    val ipv6DeviceDNS: String? = null,
    val ledMode: String? = null,
    val lacpStatus: String? = null,
    val switchForQoeRtls: String? = null,
    val qoeSwitch: String? = null,
    val rtlsSwitch: String? = null,
    val flashThreshold: String? = null,
    val memoryThreshold: String? = null,
    val cpuThreshold: String? = null,
    val bleMac: String? = null,
    val iotPrivateSwitch: Boolean? = null,
    val iotMode: String? = null,
    val advertisingSwitch: Boolean? = null,
    val frequency: Int? = null,
    val txPower: Int? = null,
    val txChannel: List<Int>? = null,
    val beaconMode: String? = null,
    val plainUrl: String? = null,
    val nameSpace: String? = null,
    val instanceId: String? = null,
    val scanningSwitch: Boolean? = null,
    val scanningInterval: Int? = null,
    val ouiWhiteList: List<String>? = null,
    val deviceCountryCode: String? = null,
    val apRadioConfigSwitch: String? = null,
    val band2: String? = null,
    val band5A: String? = null,
    val band5H: String? = null,
    val band5L: String? = null,
    val band6: String? = null,
    val _modifiedTS: String? = null,
    val callHomeInterval: Int? = null,
    val chassisInfo: String? = null,
    val currentRunningDirectory: String? = null,
    val dataVpnServerIP: String? = null,
    val deviceFeatures: String? = null,
    val deviceLicenseMode: String? = null,
    val deviceNaasMode: String? = null,
    val devicePrivateKey: String? = null,
    val devicePublicKey: String? = null,
    val deviceRole: String? = null,
    val deviceVpnIP: String? = null,
    val endIpAddress: String? = null,
    val ipAddressPoolOption: String? = null,
    val lengthIpAddress: String? = null,
    val manageRapVpnServer: String? = null,
    val manageRapVpnServerPort: Int? = null,
    val manageRapVpnServerPrivateKey: String? = null,
    val manageRapVpnServerPublicKey: String? = null,
    val networkIpAddress: String? = null,
    val ovEnterpriseServerIP: String? = null,
    val partNumber: String? = null,
    val pkiUpdateStatus: String? = null,
    val pkiUpdateTimestamp: String? = null,
    val rap: Boolean? = null,
    val startIpAddress: String? = null,
    val subnetMask: String? = null,
    val tcpMss: String? = null,
    val vcMacAddress: String? = null,
    val upTime: Int? = null,
    val bridgeApWebPassword: String? = null,
    val bridgeApWebSwitch: String? = null,
    val bridgeDefault: String? = null,
    val bridgeFarEndApIp: String? = null,
    val bridgeFarEndApMac: String? = null,
    val bridgeSshPassword: String? = null,
    val bridgeSshSwitch: String? = null,
    val bridgeWebCertName: String? = null,
    val lastRegisterEpochSecondTime: Long? = null,
    val meshMode: String? = null,
    val meshParentNode: String? = null,
    val channel: Int? = null,
    val linkStatus: String? = null,
    val registrationStatus: String? = null,
    val registrationStatusReason: String? = null,
    val version: String? = null,
    val changes: String? = null,
    val apName: String? = null,
    val encryptionType: String? = null,
    val meshMcastRate: String? = null,
    val _insertedTS: String? = null,
    val activationStatus: String? = null,
    val currentRunningSoftwareVersion: String? = null,
    val lldpSwitch: Boolean? = null,
    val lastHeartBeat: Long? = null,
    val modelName: String? = null,
    val licenseCategory: String? = null,
    val deviceLocation: String? = null,
    val workMode: String? = null,
    val managementConnectivity: String? = null,
    val rfProfile: String? = null,
    val numberOfLicensesUsed: Int? = null,
    val upgradeSchedule: UpgradeSchedule? = null,
    val desiredSwVersion: String? = null,
    val scheduleLevel: String? = null,
    val rootMacFriendlyName: String? = null
)

data class DeviceDetail(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val id: String? = null,
    val name: String? = null,
    val ipAddress: String? = null,
    val ipAddressV6: String? = null,
    val friendlyName: String? = null,
    val macAddress: String? = null,
    val serialNumber: String? = null,
    val deviceFamily: String? = null,
    val type: String? = null,
    val physicalLocation: String? = null,
    val description: String? = null,
    val systemContact: String? = null,
    val location: Location? = null,
    val floorElevation: Double? = null,
    val deviceStatus: String? = null,
    val currentSwVer: String? = null,
    val workingMode: String? = null,
    val lastSeenTime: Long? = null,
    val imageLocation: String? = null,
    val licenseStatus: String? = null,
    val autoChoosingLicenseMode: String? = null,
    val markPremium: Boolean? = null,
    val managementMode: String? = null,
    val isRap: Boolean? = null,
    val vpnSettingName: String? = null,
    val isAutoRegistered: Boolean? = null,
    val vcSerialNumber: String? = null,
    val calculatedMacAddress: String? = null,
    val organization: String? = null,
    val site: SiteBrief? = null,
    val group: Group? = null,
    val building: Building? = null,
    val floor: Floor? = null,
    val license: License? = null,
    val deviceLabels: List<DeviceLabel>? = null,
    val lastEventReceivedAt: Long? = null,
    val wiredPortLinkStatus: String? =  null,
    val iotStatus: String? = null,
    val ipMode: String? = null,
    val meshEnable: Boolean? = null,
    val meshRole: String? = null,
    val meshIsRoot: Boolean? = null,
    val meshBand: String? = null,
    val meshEssid: String? = null,
    val meshPassphrase: String? = null,
    val ipv4Netmask: String? = null,
    val ipv4Gateway: String? = null,
    val ipv4DeviceDNS: String? = null,
    val ipv6Prefixlen: String? = null,
    val ipv6Gateway: String? = null,
    val ipv6DeviceDNS: String? = null,
    val ledMode: String? = null,
    val lacpStatus: String? = null,
    val switchForQoeRtls: String? = null,
    val qoeSwitch: String? = null,
    val rtlsSwitch: String? = null,
    val flashThreshold: String? = null,
    val memoryThreshold: String? = null,
    val cpuThreshold: String? = null,
    val bleMac: String? = null,
    val iotPrivateSwitch: Boolean? = null,
    val iotMode: String? = null,
    val advertisingSwitch: Boolean? = null,
    val frequency: Int? = null,
    val txPower: Int? = null,
    val txChannel: List<Int>? = null,
    val beaconMode: String? = null,
    val plainUrl: String? = null,
    val nameSpace: String? = null,
    val instanceId: String? = null,
    val scanningSwitch: Boolean? = null,
    val scanningInterval: Int? = null,
    val ouiWhiteList: List<String>? = null,
    val deviceCountryCode: String? = null,
    val apRadioConfigSwitch: String? = null,
    val band2: String? = null,
    val band5A: String? = null,
    val band5H: String? = null,
    val band5L: String? = null,
    val band6: String? = null,
    val _modifiedTS: String ? = null,
    val callHomeInterval: Int? = null,
    val chassisInfo: String? = null,
    val currentRunningDirectory: String? = null,
    val dataVpnServerIP: String? = null,
    val deviceFeatures: String? = null,
    val deviceLicenseMode: String? = null,
    val deviceNaasMode: String? = null,
    val devicePrivateKey: String? = null,
    val devicePublicKey: String? = null,
    val deviceRole: String? = null,
    val deviceVpnIP: String? = null,
    val endIpAddress: String? = null,
    val ipAddressPoolOption: String? = null,
    val lengthIpAddress: String? = null,
    val manageRapVpnServer: String? = null,
    val manageRapVpnServerPort: Int? = null,
    val manageRapVpnServerPrivateKey: String? = null,
    val manageRapVpnServerPublicKey: String? = null,
    val networkIpAddress: String? = null,
    val ovEnterpriseServerIP: String? = null,
    val partNumber: String? = null,
    val pkiUpdateStatus: String? = null,
    val pkiUpdateTimestamp: String? = null,
    val rap: Boolean? = null,
    val startIpAddress: String? = null,
    val subnetMask: String? = null,
    val tcpMss: String? = null,
    val vcMacAddress: String? = null,
    val upTime: Int? = null,
    val bridgeApWebPassword: String? = null,
    val bridgeApWebSwitch: String? = null,
    val bridgeDefault: String? = null,
    val bridgeFarEndApIp: String? = null,
    val bridgeFarEndApMac: String? = null,
    val bridgeSshPassword: String? = null,
    val bridgeSshSwitch: String? = null,
    val bridgeWebCertName: String? = null,
    val lastRegisterEpochSecondTime: Long? = null,
    val meshMode: String? = null,
    val meshParentNode: String? = null,
    val channel: Int? = null,
    val linkStatus: String? = null,
    val registrationStatus: String? = null,
    val registrationStatusReason: String? = null,
    val version: String? = null,
    val changes: String? = null,
    val apName: String? = null,
    val encryptionType: String? = null,
    val meshMcastRate: String? = null,
    val _insertedTS: String? = null,
    val activationStatus: String? = null,
    val currentRunningSoftwareVersion: String? = null,
    val lldpSwitch: Boolean? = null,
    val lastHeartBeat: Long? = null,
    val modelName: String? = null,
    val licenseCategory: String? = null,
    val deviceLocation: String? = null,
    val workMode: String? = null,
    val managementConnectivity: String? = null,
    val rfProfile: String? = null,
    val numberOfLicensesUsed: Int? = null,
    val upgradeSchedule: UpgradeSchedule? = null,
    val desiredSwVersion: String? = null,
    val scheduleLevel: String? = null,
    val rootMacFriendlyName: String? = null
)

data class Location(
    val type: String? = null,
    val coordinates: List<Double>? = null
)

data class SiteBrief(
    val id: String? = null,
    val name: String? = null
)

data class Group(
    val id: String? = null,
    val name: String? = null,
    val upgradeSchedule: UpgradeSchedule? = null,
    val desiredSwVersion: String? = null
)

data class UpgradeSchedule(
    val id: Int? = null,
    val scheduleName: String? = null,
    val cronExpression: String? = null,
    val startDate: Long? = null,
    val endDate: Long? = null,
    val timeZone: String? = null,
    val duration: Long? = null,
    val state: String? = null,
    val nextTriggerTime: Long? = null,
    val prevTriggerTime: Long? = null,
    val maxScope: String? = null,
    val orgId: String? = null
)

data class Building(
    val id: String,
    val name: String
)

data class Floor(
    val id: String,
    val name: String,
    val floorNumber: Int
)

data class License(
    val maxCount: Int,
    val currentCount: Int,
    val productId: String,
    val expiredDate: String,
    val gracePeriod: Int,
    val available: Int,
    val percentUsed: String
)

data class DeviceLabel(
    val id: String,
    val name: String,
    val color: String
)


